version: 2.1

orbs:
 android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
        
    steps:
      - checkout
      - run:
          command: ./csc207/phase2/gradlew build
                   ./csc207/phase2/gradlew test
